version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - django
        volumes_from:
            - django
        volumes:
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    django:
        build: .
        command: gunicorn api.wsgi:application -w 2 -b :8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - database
    database:
        image: merorafael/postgres:9.5
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123qwe
            - POSTGRES_DB=restapi
        volumes:
            - /var/lib/postgresql/data:/var/lib/postgresql/data